services:

  postgres-server:
    image: postgres:16-alpine
    container_name: monitoring-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ZabbixDB@2026
      POSTGRES_DB: zabbix
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - zabbix-monitoring

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.0-alpine-latest
    container_name: monitoring-zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ZabbixDB@2026
      POSTGRES_DB: zabbix
    depends_on:
      - postgres-server
    ports:
      - "10051:10051"
    networks:
      - zabbix-monitoring

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:7.0-alpine-latest
    container_name: monitoring-zabbix-web
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ZabbixDB@2026
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Kolkata
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - "8083:8080"
    networks:
      - zabbix-monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring-grafana
    restart: unless-stopped
    ports:
      - "3004:3000"
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - zabbix-web
    networks:
      - zabbix-monitoring

volumes:
  postgres-data:
  grafana-data:

networks:
  zabbix-monitoring:
    driver: bridge
